Importing numpy library.

In [1]:
import numpy as np

We can create a NumPy ndarray object by using the array() function.

In [4]:
#Creating array
arr= np.array([1,2,3,4,5,6,7,8,9,10])

In [5]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


We can create a new array of any shape and type, with each element 0 using zeros() function.

In [7]:
zero_arr= np.zeros(3)

In [8]:
print(zero_arr)

[0. 0. 0.]


We can create a new array of any shape and type, with each element 1 using ones() function.

In [9]:
ones_arr= np.ones(5)

In [10]:
print(ones_arr)

[1. 1. 1. 1. 1.]


We can change the shape of array using reshape() function.

In [11]:
arr2 = np.arange(8)

In [12]:
print(arr2)

[0 1 2 3 4 5 6 7]


In [14]:
arr2.shape

(8,)

In [17]:
arr2_reshape= arr2.reshape(2,4)
arr2_reshape.shape

(2, 4)

In [18]:
print(arr2_reshape)

[[0 1 2 3]
 [4 5 6 7]]


We can join arrays using concatenate() function.

In [19]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr = np.concatenate((arr1, arr2))


In [20]:
print(arr)

[1 2 3 4]


In [21]:
arr.shape

(4,)

We can find mean of array elements using mean() function.

In [22]:
arr= np.array([1,20,39,23,17])

In [23]:
mean= np.mean(arr)

In [24]:
print(mean)

20.0


We can find sum of array elements using sum() function.

In [25]:
arr= np.array([1,20,39,23,17])

In [26]:
sum= np.sum(arr)

In [27]:
print(sum)

100


We can find minimum element in array using min() function.

In [28]:
arr= np.array([1,20,39,23,17])

In [29]:
print(np.min(arr))

1


We can find maximum element in array using max() function.

In [30]:
arr= np.array([1,20,39,23,17])

In [31]:
print(np.max(arr))

39


We can find index of the minimum element in array using argmin() function.

In [37]:
arr= np.array([9,1,39,23,17])

In [38]:
print(np.argmin(arr))

1


NOTE- When there are two min elements in array, argmin will return index of the first occurence of the minimum element.

In [39]:
arr= np.array([9,1,39,1,17])

In [40]:
print(np.argmin(arr))

1


We can find index of the maximum element in array using argmax() function.

In [41]:
arr= np.array([9,1,39,23,17])

In [42]:
print(np.argmax(arr))

2


NOTE- When there are two max elements in array, argmax will return index of the first occurence of the maximum element.

In [43]:
arr= np.array([39,1,39,23,17])

In [44]:
print(np.argmax(arr))

0


We can find dot product using dot() function.

In [45]:
#Element mutliplication
np.dot(4,5)

20

In [46]:
#If both a and b are 1-D arrays, it is inner product of vectors.
np.dot([2, 3], [3, 4])

18

In [47]:
#If both a and b are 2-D arrays, it is matrix multiplication.
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

np.random.rand() creates an array of any shape with random values over [0,1).
This function generates random numbers from a **uniform distribution**.

In [50]:
arr= np.random.rand(2,4)

In [51]:
print(arr)

[[0.91270229 0.11502433 0.98052356 0.80147561]
 [0.51865342 0.32673252 0.33010839 0.30690753]]


np.random.randn() creates an array of any shape with random values.
This function generates random numbers from a **standard normal distribution**.
The standard normal distribution is a probability distribution where the mean is 0 and the standard deviation is 1.

In [52]:
arr= np.random.randn(2,4)

In [53]:
print(arr)

[[-0.65967943 -0.36198894 -1.55007618 -1.57707382]
 [-0.68490854 -0.575343   -0.39379756  0.23986786]]


np.random.randint() creates an array of any shape with random integers between a specified range.

In [58]:
arr= np.random.randint(2,6,size=(2,5))
print(arr)

[[5 3 5 3 5]
 [4 3 3 5 2]]


In this case the range is [2,6).